### PR TITLE
[WIP] Graphy graph

### PR DESCRIPTION
**Pull request by pmarsceill**
Starting to spike out a graph branch..

This PR:
- Brings in the d3 library for graphing
- Spits out a JSON version of the log data (for easier graphing / manipulation)

Todo:
- [ ] Make sure this JSON format will work
- [ ] Hook up d3 to actually chart this data

/cc @josh

### CODE REVIEW

**Comment by pmarsceill** [comment]
JSON is formatted like:

``` json
[{"dateTime":"Tue May 31 2016 16:39:14 GMT-0400 (EDT)","eventType":"open"},{"dateTime":"Tue May 31 2016 16:39:14 GMT-0400 (EDT)","eventType":"active"}]
```

**Comment by josh** [comment]
:metal:

**Comment by pmarsceill** [comment]
Trying to figure out a good format for graphing and I think we're going to need to manipulate the JSON a bit to determine the following metrics (to start):
- App opens / exits per day
- Total length of active time per day
- Total length of active time  per hour
- Total length of idle time per day
- Total length of idle time per hour
- Stretches of consecutive active time per day
- Stretches of consecutive idle time per day

It kind of hurts my brain to think about how to calculate this and process it. @josh do you have any suggestions for either other metrics we should track or ways to calculate the metrics with the JSON?

**Comment by pmarsceill** [comment]
Closing this in favor of refactored log format.

**Comment by josh** [comment]
> Closing this in favor of refactored log format.

🔜

**Pull request closed without merging**
