### PR TITLE
Update marketing page Mac App Store link

### PR DESCRIPTION
**Pull request by josh**
screen shot 2016-04-09 at 10 45 09 am

@pmarsceill does this look okay? Any copy or style suggestions?

### CODE REVIEW

**Comment by pmarsceill** [comment]
Looks fine, but wondering if we should use the official "App store badge" instead?

https://developer.apple.com/app-store/marketing/guidelines/#downloadOnAppstore

I can't tell if these re iOS guidelines or OS X guidelines or both??

**Comment by josh** [comment]
Oh, yeah, forgot theres a badge. I'd be down with that.

**Comment by pmarsceill** [comment]
> Oh, yeah, forgot theres a badge. I'd be down with that.

Cool, I'll get this going today.

**Comment by pmarsceill** [comment]
@josh Got the badge / link in place and moved the app icon to the footer.

screen shot 2016-04-11 at 1 17 33 pm

---

screen shot 2016-04-11 at 1 17 52 pm

**Pull request merged**
