### PR TITLE
[WIP] App icon update

### PR DESCRIPTION
**Pull request by pmarsceill**
Just updating the app icon to the new jam:

aware icon

### CODE REVIEW

**Comment by pmarsceill** [comment]
Ref: #26

**Comment by josh** [comment]
Nice! I missed this.

Should we merge?

**Comment by pmarsceill** [comment]
I was going to throw all the other icon updates here too.

**Comment by pmarsceill** [comment]
@josh I think this is ready for :eyes: then a merge!

**Comment by josh** [comment]
Hell yeah!

**Comment by josh** [comment]
I'll get this baby submitted to the app store today!

**Pull request merged**
