### PR TITLE
Let's introduce our app to the world

### PR DESCRIPTION
**Pull request by pmarsceill**
This PR adds responsive styles for content, a little in browser demo, and additional content.

screen shot 2016-02-15 at 2 28 45 pm

### CODE REVIEW

**Comment by pmarsceill** [comment]
Responsive styles:

screen shot 2016-02-15 at 2 42 09 pm

screen shot 2016-02-15 at 2 42 52 pm

screen shot 2016-02-15 at 2 43 25 pm

**Comment by pmarsceill** [comment]
@josh I hit you up in Slack, but just leaving a note here for posterity.

I think it'd be rad to do three small things:
1. Create a switch to go into dark mode (this should be easy as everything is CSS / SVG. All we would need to do is change the `.menubar` bg color, text color, and svg fill color).
2. Write a little JS that makes the clock accurate to system time.
3. Possibly write a little JS that will start the Aware timer on page load (not that anyone will stay on this page for > 1 minute to see it change, but it'd be slick!)

Thoughts?

**Comment by josh** [comment]
This is totally badass!

> I think it'd be rad to do three small things:

Awesome idea! I love that you reproduced with the menu bar with html and css. We could totally make that work!

❤️

**Comment by josh** [comment]
:metal:

**Pull request merged**
