### PR TITLE
Gitignore

### PR DESCRIPTION
**Pull request by pmarsceill**
This PR adds a `.gitignore` file for OSX and Swift based projects.

It is based on:
- https://github.com/github/gitignore/blob/master/Swift.gitignore
- https://github.com/github/gitignore/blob/master/Global/OSX.gitignore

### CODE REVIEW

**Comment by josh** [comment]
Theres one already in https://github.com/josh/Aware/blob/master/Aware.xcodeproj/.gitignore

Was there some specific file that showed up as dirty on your machine that we should add?

**Comment by pmarsceill** [comment]
I getting `.DS_Store` in the root. I realized I was also tracking from root, not from within `Aware.xcodeproj` Changing my behavior will probably fix it :)

**Comment by josh** [comment]
We can probably drop `.DS_Store` at the root of the project. Though, I usually ignore that in my global `~/.gitignore` so its ignored from any project I'm working on.

**Comment by pmarsceill** [comment]
I didn't even know that one could do such a thing :smile:  I'll add it and then :fire: this PR.

**Comment by josh** [comment]
Theres one more step if you're creating that file for the first time.

```
$ git config --global core.excludesfile ~/.gitignore_global
```

https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Pull request closed without merging**
